#!/usr/bin/env python
from argparse import ArgumentParser
from shlex import quote, split
from subprocess import run

parser = ArgumentParser("jlox")
parser.add_argument("script", nargs='?', default=None)
args = parser.parse_args()

cmd = split("java -ea com.craftinginterpreters.lox.Lox")
if args.script:
    cmd.append(quote(args.script))

try:
    run(cmd)
except Exception:
    pass
except KeyboardInterrupt:
    pass
